// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFTcHLU788NBMZPDetQZiU7woiGUto-B8',
    appId: '1:231566288621:web:2b8cbb2ca71f245fb70ee4',
    messagingSenderId: '231566288621',
    projectId: 'arunika-ba5d4',
    authDomain: 'arunika-ba5d4.firebaseapp.com',
    storageBucket: 'arunika-ba5d4.firebasestorage.app',
    measurementId: 'G-YD6NVQ1KCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1p2r9pUGp79vB-Wa2070DmjDiqtIjSZU',
    appId: '1:231566288621:android:bae6ed7dd67fd2f4b70ee4',
    messagingSenderId: '231566288621',
    projectId: 'arunika-ba5d4',
    storageBucket: 'arunika-ba5d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARkb6oKa1rUjL53RDUh5AKmw5CmJmZias',
    appId: '1:231566288621:ios:f46626002a4b433cb70ee4',
    messagingSenderId: '231566288621',
    projectId: 'arunika-ba5d4',
    storageBucket: 'arunika-ba5d4.firebasestorage.app',
    iosBundleId: 'com.example.arunika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARkb6oKa1rUjL53RDUh5AKmw5CmJmZias',
    appId: '1:231566288621:ios:f46626002a4b433cb70ee4',
    messagingSenderId: '231566288621',
    projectId: 'arunika-ba5d4',
    storageBucket: 'arunika-ba5d4.firebasestorage.app',
    iosBundleId: 'com.example.arunika',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFTcHLU788NBMZPDetQZiU7woiGUto-B8',
    appId: '1:231566288621:web:bc2b6b6269ecf45db70ee4',
    messagingSenderId: '231566288621',
    projectId: 'arunika-ba5d4',
    authDomain: 'arunika-ba5d4.firebaseapp.com',
    storageBucket: 'arunika-ba5d4.firebasestorage.app',
    measurementId: 'G-N5MD0HZ8BN',
  );
}